# Number of days of inactivity before an issue/PR is marked as stale
daysUntilStale: 60

# Number of days of inactivity after marking an issue/PR as stale, is then closed.
daysUntilClose: 7

# Issues/PR with these labels will never be considered stale
exemptLabels:
  - pinned
  - security

# Label to use when marking an issue/PR as stale
staleLabel: wontfix

# Comment to post when marking an issue/PR as stale. Set to `false` to disable
markComment: >
  This issue has been automatically marked as stale because it has not had
  recent activity. It will be closed if no further activity occurs. Thank you
  for your contributions.

# Comment to post when closing a stale issue/PR. Set to `false` to disable
closeComment: false
