language: minimal
os: linux
dist: xenial

# --------------------------------- Travis ----------------------------------
notifications:
  email: false

branches:
  # Ensures when "Build pushed branches is enabled" in Travis setting, then only the below branches will execute the build
  # Note: When "Build pushed pull requests" is enabled then all open PR are built with every commit pushed.
  only:
    - master
    - develop

git:
  depth: false
  quiet: true

# --------------------------------- ENV ----------------------------------
env:
  global:
    # for updates check developer.android.com/studio#downloads
    - ANDROID_SDK_TOOLS=commandlinetools-linux-6200805_latest.zip
    - ANDROID_SDK_VERS=29
    - ANDROID_BUILD_TOOLS_VERS=29.0.3

# --------------------------------- Install ----------------------------------
before_install:
  - openssl aes-256-cbc -K $encrypted_48536eba9c94_key -iv $encrypted_48536eba9c94_iv -in ./keystore/keystore.jks.enc -out ./keystore/keystore.jks -d
  # Set JAVA_HOME path
  - export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
  # Download and unzip Android SDK command line tools
  - wget -nv https://dl.google.com/android/repository/$ANDROID_SDK_TOOLS
  - unzip -q -n $ANDROID_SDK_TOOLS -d $HOME/sdk
  # Set SDK tools path variable and ANDROID_HOME
  - export PATH=$PATH:$HOME/sdk/tools/bin
  - export ANDROID_HOME=$HOME/sdk
  # Create empty cfg file to prevent sdkmanager warning message
  - mkdir -p $HOME/.android && touch $HOME/.android/repositories.cfg

install:
  # Install android sdk and build tools
  - yes | "${ANDROID_HOME}/tools/bin/sdkmanager" --sdk_root=${ANDROID_HOME} "platforms;android-${ANDROID_SDK_VERS}" > /dev/null
  - yes | "${ANDROID_HOME}/tools/bin/sdkmanager" --sdk_root=${ANDROID_HOME} "build-tools;${ANDROID_BUILD_TOOLS_VERS}" > /dev/null
  # Install fastlane
  - bundle install
  - fastlane install_plugins

# --------------------------------- Cache ----------------------------------
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -rf $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - .gradle
    - $HOME/.android/build-cache
    - $HOME/.m2/repository
    - $HOME/sdk

# --------------------------------- Script ----------------------------------
before_script:
  # Make scripts and gradlew executable
  - chmod +x gradlew
  # Setup signing config
  - echo "storePassword=$storePassword" >> ./keystore/keystore.properties
  - echo "keyAlias=$keyAlias" >> ./keystore/keystore.properties
  - echo "keyPassword=$keyPassword" >> ./keystore/keystore.properties
  # Setup gradle.properties
  - mkdir -p $HOME/.gradle
  - echo "org.gradle.daemon=false" >> $HOME/.gradle/gradle.properties
  - echo "org.gradle.console=plain" >> $HOME/.gradle/gradle.properties

stages:
  - name: build_test_coverage
  - name: deploy
    if: (type != pull_request) AND (branch = master) AND (tag IS present)

jobs:
  fast_finish: true
  include:
    # Build, Test & Code Coverage
    - stage: build_test_coverage
      name: "Build, execute unit tests and generate code coverage for the codebase"
      script:
        - bundle exec fastlane run_ci
    # Deploy
    - stage: deploy
      name: "Assemble release APK"
      script:
        - bundle exec fastlane assemble_release_apk

# ------------------------ Deploy to Github Releases ------------------------
before_deploy:
  - cd app/build/outputs/apk/

deploy:
  provider: releases
  skip_cleanup: true
  overwrite: true
  api_key:
    secure: "Q9IQZj0AXqSJP8mTCzutMQbeZIUB0iSXgfJuOowZaesot2nt4rL1vZjUPewmn+uTnM7JW8zS0+3c54WnUiHknYnMMaN8jezZHzgZvoGjA+Tg1qXW7+5TqTTiMTZ0F2+/iXzwrDyd/WNhPmcSBK1IhvTCM/twL4CRNvuaaoePENlgEdJe4ApC+wTs3t3WiEsrx8W+yIgHJn80g8HXx1f/+Wb2JQ9RFEf+2GIDMibAY89Bk/d8E9+ptD4Xaf7cHMHDfM4MZY/bMc3kgZkbFFewi7F9XG0HDI8D6DDOPFP6H7e18RVPaqqSxLS2d2+3XcRIjX0DdOpM6mnezwzRQ0KZTna8aVky+gPOJRtKNvaWOm/FAtKYTzWIr7EMxcu3YkrNG1W2/AlC8IFg27FVaAGrj2EmroEbVpFD9a4eO3RRnelqhhlShsy0C2k/xLySG/cmejnptf4TsxmWOsCHzzYWcjxu6LcnfM6d3Yf2CiQAbAMu8iloONNBMSfgVOI71IFPKyhrUJbfaUIg6c55ZQRbkXhBA7FD5mWVEo4vKgZo+nSA3yqoaQLytTFE0OTDCfcD12SKO1BdPuJGd1RVTt39J5MbCqShZkusiGeQxXF2clZJMkQ9lF6mLr1t4S4x/XGUfFyf/42H330Bjt5dboySDaygXCFOvPDyFZYa5/js7ZY="
  file_glob: true
  file: release/app-release.apk
  on:
    repo: nisrulz/AndroidAutomations
    tags: true
